[package]
name = "mycelium-python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
ndarray = "0.15"
mycelium-dsp = { path = "../mycelium-dsp" }
mycelium-lang = { path = "../mycelium-lang" }

[lib]
crate-type = ["cdylib"]
